# Generated by Django 4.1.1 on 2022-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('isAvailable', models.BooleanField()),
                ('detail', models.TextField()),
                ('ratings', models.FloatField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
