# Generated by Django 4.1.1 on 2022-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shippingCharge',
            field=models.FloatField(null=True),
        ),
    ]
